---
- name: Create User Account
  hosts: all
  roles:
    - name: Create User Account
      role: useradd

- name: Create User Account
  hosts: all
  roles:
    - name: Create User Account
      role: useradd

